version: '3'
services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    environment:
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - .:/output
    - ./manifests/edipogram-deploy.yml:/var/lib/rancher/k3s/server/manifests/edipogram-deploy.yml
    ports:
    - "6443:6443"  # Kubernetes API Server
    - "443:443"
    - "8080:80"

volumes:
  k3s-server: {}