version: '3.8'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ../../api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"

  enigmi:
    container_name: enigmi
    build:
      context: ../../enigmi
    image: enigmi:latest

  connessioni:
    container_name: connessioni
    build:
      context: ../../connessioni
    image: connessioni:latest

  enigmi-seguiti:
    container_name: enigmi-seguiti
    build:
      context: ../../enigmi-seguiti
    image: enigmi-seguiti:latest

  consul:
    container_name: consul
    image: consul
    restart: always

  db-enigmi:
    container_name: db-enigmi
    image: postgres
    volumes:
      - ../../enigmi/src/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    restart: always
    environment:
      POSTGRES_DB: enigmi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  db-enigmi-seguiti:
    container_name: db-enigmi-seguiti
    image: postgres
    volumes:
      - ../../enigmi-seguiti/src/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    restart: always
    environment:
      POSTGRES_DB: enigmi-seguiti
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  db-connessioni:
    container_name: db-connessioni
    image: postgres
    volumes:
      - ../../connessioni/src/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    restart: always
    environment:
      POSTGRES_DB: connessioni
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://kafka-broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
